export const DASHBOARD_DATA_REG = [
    {
      id: 1,
      title: "Soal TP",
      openDate: "15 Juli 2024",
      closeDate: "18 Juli 2024",
      status: "CLOSED",
      // link1: "https://docs.google.com/document/d/1m8ofCHZ4RhE7QHlynK4uGAvd-0KWr_IuBvQAqkWNkP4/edit?usp=drive_link",
      // link2: "https://docs.google.com/document/d/1iaTCMT7GLykiGh0kwmEMCAYby-mw9RCowW6O65fYexs/edit?usp=drive_link",
    },
    {
      id: 2,
      title: "Soal TA",
      openDate: "20 Juli 2024",
      closeDate: "20 Juli 2024",
      status: "ON-GOING",
      // link1: "https://forms.gle/KZM21HbWYcHQLhw98",
      link2: "https://forms.gle/mj3n7EGTgbyqsztz5",
    },
    {
      id: 3,
      title: "Soal TK",
      openDate: "20 Juli 2024",
      closeDate: "20 Juli 2024",
      status: "ON-GOING",
      // link1: "https://forms.gle/w2mk7h7m5Cd2dc5K9",
      link2: "https://forms.gle/oSKhnshehpnvam7dA",
    },
    {
      id: 4,
      title: "JURNAL",
      openDate: "20 Juli 2024",
      closeDate: "20 Juli 2024",
      status: "ON-GOING",
      // link1: "https://docs.google.com/document/d/1lzqEcKcbo9u3DNpyXv-bHb2505unBBO_/edit?usp=drive_link&ouid=107866615986334911734&rtpof=true&sd=true",
      link2: "https://docs.google.com/document/d/1STnDuqwPxQLHjCnZe_5cTv3exUtzrGEB/edit?usp=drive_link&ouid=107866615986334911734&rtpof=true&sd=true",
    },
    {
      id: 5,
      title: "MANDIRI",
      openDate: "20 Juli 2024",
      closeDate: "20 Juli 2024",
      status: "ON-GOING",
      // link1: "https://docs.google.com/document/d/1F2pBCJ6x-92pObhEkuB7jg7_FSNv9ffh/edit?usp=drive_link&ouid=107866615986334911734&rtpof=true&sd=true",
      link2: "https://docs.google.com/document/d/1DJaxMmwyMxxJyZvh_gMNKBbg2qTqLV89/edit?usp=drive_link&ouid=107866615986334911734&rtpof=true&sd=true",
    },
    {
      id: 6,
      title: "TUBES",
      openDate: "3 Agustus 2024",
      closeDate: "16 Agustus 2024",
      status: "COMING-SOON",
      // link1: "/tubes",
      // link2: "/tubes",
    },
  ];

  export const DASHBOARD_DATA_INTER = [
    {
      id: 1,
      title: "TP Assignment",
      openDate: "July 15, 2024",
      closeDate: "July 18, 2024",
      status: "CLOSED",
      // link1: "https://docs.google.com/document/d/1cVVMfnpEh9nrZtiFrCyIk978_jvG_O_Zzfr2EGFrMXE/edit?usp=drive_link",
      // link2: "https://docs.google.com/document/d/1J6cXIDg0flOIWDCjaOgZFFJBil7P2jSHTYq619MrBMg/edit?usp=drive_link",
    },
    {
      id: 2,
      title: "TA Assignment",
      openDate: "July 19, 2024",
      closeDate: "July 20, 2024",
      status: "ON-GOING",
      // link1: "https://forms.gle/YPpA9EremAg4WPEQ6",
      link2: "https://forms.gle/v2CzLk9wnpHhVsrE7",
    },
    {
      id: 3,
      title: "TK Assignment",
      openDate: "July 19, 2024",
      closeDate: "July 20, 2024",
      status: "ON-GOING",
      // link1: "https://forms.gle/4ThCXhcHtmh9LRDv9",
      link2: "https://forms.gle/zQKCooNPENjQ9KmL6",
    },
    {
      id: 4,
      title: "Journal",
      openDate: "July 19, 2024",
      closeDate: "July 20, 2024",
      status: "ON-GOING",
      // link1: "https://docs.google.com/document/d/1IlJ99ltCHXjvF_nGPpZbjwOl2qR2x07P/edit?usp=drive_link",
      link2: "https://docs.google.com/document/d/1fUHrkbwGxtKwSw3KgqGS_Y4afcGNKcxF/edit?usp=drive_link",
    },
    {
      id: 5,
      title: "Independent Assignment",
      openDate: "July 19, 2024",
      closeDate: "July 20, 2024",
      status: "ON-GOING",
      // link1: "https://docs.google.com/document/d/1Asl_n_HaSA1Ut2BhoEG4qUQMF_R8CKFl/edit?usp=drive_link",
      link2: "https://docs.google.com/document/d/175s5KsuHcK_6N8P2X9wUSIGO63ezNSNd/edit?usp=drive_link&ouid=107866615986334911734&rtpof=true&sd=true",
    },
    {
      id: 6,
      title: "Project",
      openDate: "August 3, 2024",
      closeDate: "August 15, 2024",
      status: "ON-GOING",
      // link1: "/tp",
      // link2: "/tp",
    },
  ];
  
  